---
parameters:
- name: IMAGE
  value: "quay.io/redhat-user-workloads/assisted-installer-tenant/assisted-service-mcp-saas-main/assisted-service-mcp-saas-main"
  description: "Container image for the assisted service Model Context Protocol (MCP) server"
- name: IMAGE_TAG
  value: ''
  required: true
  description: "Tag of the container image to deploy"
- name: INVENTORY_URL
  value: "https://api.openshift.com/api/assisted-install/v2"
  description: "URL for the assisted installer inventory API endpoint"
- name: SSO_URL
  value: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
  description: "URL for Red Hat Single Sign-On (SSO) OpenID Connect token endpoint"
- name: PULL_SECRET_URL
  value: "https://api.openshift.com/api/accounts_mgmt/v1/access_token"
  description: "URL for accessing pull secrets via the accounts management API"
- name: REPLICAS_COUNT
  value: "1"
  description: "Number of pod replicas to deploy for high availability"
- name: CLIENT_DEBUG
  value: "false"
  description: "Whether to enable debug logging for the MCP client (True/False)"
- name: SERVICE_PORT
  value: "8000"
  description: "Port number on which the MCP service listens"
- name: MEMORY_LIMIT
  value: "128Mi"
  description: "Maximum memory allocation for the container"
- name: CPU_LIMIT
  value: "100m"
  description: "Maximum CPU allocation for the container (in millicores)"
- name: MEMORY_REQUEST
  value: "64Mi"
  description: "Initial memory request for the container"
- name: CPU_REQUEST
  value: "50m"
  description: "Initial CPU request for the container (in millicores)"

apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: assisted-service-mcp
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: assisted-service-mcp
    name: assisted-service-mcp
  spec:
    replicas: ${{REPLICAS_COUNT}}
    selector:
      matchLabels:
        app: assisted-service-mcp
    template:
      metadata:
        labels:
          app: assisted-service-mcp
      spec:
        containers:
        - name: assisted-service-mcp
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: ${{SERVICE_PORT}}
            protocol: TCP
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          env:
          - name: INVENTORY_URL
            value: ${INVENTORY_URL}
          - name: SSO_URL
            value: ${SSO_URL}
          - name: PULL_SECRET_URL
            value: ${PULL_SECRET_URL}
          - name: CLIENT_DEBUG
            value: ${CLIENT_DEBUG}
- apiVersion: v1
  kind: Service
  metadata:
    name: assisted-service-mcp
    labels:
      app: assisted-service-mcp
  spec:
    selector:
      app: assisted-service-mcp
    ports:
      - protocol: TCP
        port: ${{SERVICE_PORT}}
        targetPort: ${{SERVICE_PORT}}

