---
parameters:
- name: IMAGE
  value: "quay.io/redhat-user-workloads/assisted-installer-tenant/assisted-service-mcp-saas-main/assisted-service-mcp-saas-main"
- name: INVENTORY_URL
  value: "https://api.openshift.com/api/assisted-install/v2"
- name: SSO_URL
  value: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
- name: PULL_SECRET_URL
  value: "https://api.openshift.com/api/accounts_mgmt/v1/access_token"
- name: REPLICAS_COUNT
  value: "1"
- name: CLIENT_DEBUG
  value: "False"
- name: SERVICE_PORT
  value: "8000"
- name: MEMORY_LIMIT
  value: "128Mi"
- name: CPU_LIMIT
  value: "100m"
- name: MEMORY_REQUEST
  value: "64Mi"
- name: CPU_REQUEST
  value: "50m"

apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: assisted-service-mcp
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: assisted-service-mcp
    name: assisted-service-mcp
  spec:
    replicas: ${REPLICAS_COUNT}
    selector:
      matchLabels:
        app: assisted-service-mcp
    template:
      metadata:
        labels:
          app: assisted-service-mcp
      spec:
        containers:
        - name: assisted-service-mcp
          image: ${IMAGE}
          ports:
          - containerPort: ${SERVICE_PORT}
            protocol: TCP
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          env:
          - name: INVENTORY_URL
            value: ${INVENTORY_URL}
          - name: SSO_URL
            value: ${SSO_URL}
          - name: PULL_SECRET_URL
            value: ${PULL_SECRET_URL}
          - name: CLIENT_DEBUG
            value: ${CLIENT_DEBUG}
- apiVersion: v1
  kind: Service
  metadata:
    name: assisted-service-mcp
    labels:
      app: assisted-service-mcp
  spec:
    selector:
      app: assisted-service-mcp
    ports:
      - protocol: TCP
        port: ${SERVICE_PORT}
        targetPort: ${SERVICE_PORT}

